# Dependencies
markdown:         redcarpet
highlighter:      rouge
# Permalinks
permalink:        pretty

# Setup
title:            Loftus.xyz
tagline:          'Always Exploring'
description:      
url:              https://loftus.xyz

author:
  name:           'Matt Loftus'
  url:            https://twitter.com/MastaYu

paginate:         5

gems:             [jekyll-paginate]
# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/MattLoftus.github.com
